name: Persistent Tailscale Node

on:
  workflow_dispatch:

jobs:
  tailscale-node:
    runs-on: self-hosted  # Use your self-hosted runner
    timeout-minutes: 4320 # Up to 72 hours

    steps:
      - name: Update System
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y curl ufw

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Bring Up Tailscale Node
        run: |
          if [ -z "${{ secrets.TAILSCALE_AUTH_KEY }}" ]; then
            echo "Error: TAILSCALE_AUTH_KEY secret not set"
            exit 1
          fi
          HOSTNAME="gh-node-$GITHUB_RUN_ID"
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=$HOSTNAME

          # Wait a few seconds for IP assignment
          sleep 5
          TS_IP=$(tailscale ip -4)
          if [ -z "$TS_IP" ]; then
            echo "Tailscale IP not assigned. Exiting."
            exit 1
          fi
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Display Node Info
        run: |
          echo "=== Tailscale Node Active ==="
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Hostname: gh-node-$GITHUB_RUN_ID"
          echo "This node stays connected to the tailnet but does NOT route internet traffic."
      
      - name: Keep Runner Alive
        run: |
          echo "Runner is alive. Press Ctrl+C to stop..."
          while true; do
            sleep 300
          done
