name: Tailscale VPN Setup

on:
  workflow_dispatch:

jobs:
  tailscale-vpn:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Update & Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl iproute2

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale with Auth Key
        run: |
          # Bring up Tailscale using GitHub secret
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          
          # Wait a few seconds for IP assignment
          sleep 5

          # Verify Tailscale IP
          TS_IP=$(tailscale ip -4)
          if [ -z "$TS_IP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Display Tailscale Connection Info
        run: |
          echo "=== Tailscale VPN Active ==="
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Hostname: gh-runner-$GITHUB_RUN_ID"
          echo "============================"
