name: Setup VPS Tailscale

on:
  workflow_dispatch:

jobs:
  tailscale-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect VPS to Tailscale
        run: |
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --accept-routes --accept-dns

      - name: Show Tailscale Status
        run: tailscale status
