name: Remote Access Ubuntu

on:
  workflow_dispatch:

jobs:
  secure-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Update & Install Core Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xrdp ufw wget curl

      - name: Configure XRDP
        run: |
          # Enable XRDP service
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
          # Allow XRDP port through firewall
          sudo ufw allow 3389/tcp
          sudo ufw reload

      - name: Create RDP User with Secure Password
        run: |
          # Generate a strong password
          PASSWORD=$(tr -dc 'A-Za-z0-9@#$%&*' </dev/urandom | head -c 16)
          USERNAME="rdpuser"
          sudo useradd -m -s /bin/bash $USERNAME
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          # Wait for Tailscale IP
          for i in {1..10}; do
              TAILSCALE_IP=$(tailscale ip -4)
              if [ -n "$TAILSCALE_IP" ]; then break; fi
              sleep 5
          done
          if [ -z "$TAILSCALE_IP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV

      - name: Verify XRDP Accessibility
        run: |
          if ! nc -zv $TAILSCALE_IP 3389; then
              echo "TCP connection to XRDP port 3389 failed"
              exit 1
          fi
          echo "TCP connectivity successful!"

      - name: Display Access Info
        run: |
          echo "=== XRDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: rdpuser"
          echo "Password: $RDP_CREDS"
          echo "=================="
