name: Tailscale VPN Exit Node

on:
  workflow_dispatch:

jobs:
  tailscale-vpn:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Update & Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl iptables

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale with Auth Key
        run: |
          # Bring up Tailscale with hostname and auth key
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID --advertise-exit-node
          
          # Wait a few seconds for IP assignment
          sleep 5

          # Verify Tailscale IP
          TS_IP=$(tailscale ip -4)
          if [ -z "$TS_IP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Enable NAT for Exit Node
        run: |
          # Enable IP forwarding
          sudo sysctl -w net.ipv4.ip_forward=1

          # Set up NAT using iptables
          sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
          sudo iptables -A FORWARD -i tailscale0 -o eth0 -j ACCEPT
          sudo iptables -A FORWARD -i eth0 -o tailscale0 -m state --state ESTABLISHED,RELATED -j ACCEPT

      - name: Display Tailscale Exit Node Info
        run: |
          echo "=== Tailscale Exit Node Active ==="
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Hostname: gh-runner-$GITHUB_RUN_ID"
          echo "Now you can enable this exit node on your Tailscale client"
          echo "================================="
