name: RDP + Tailscale (secure)

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install Tailscale (winget)
        shell: powershell
        run: |
          Write-Host "Installing Tailscale..."
          winget install --id Tailscale.Tailscale -e --accept-package-agreements --accept-source-agreements
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")

      - name: Start Tailscale service
        shell: powershell
        run: |
          Write-Host "Starting Tailscale service..."
          Start-Service -Name "Tailscale" -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 4
          Get-Service -Name "Tailscale"

      - name: Bring up Tailscale using secret auth key
        shell: powershell
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          if (-not $env:TAILSCALE_AUTH_KEY) {
            Write-Error "TAILSCALE_AUTH_KEY secret not set"
            exit 1
          }
          tailscale up --authkey="$env:TAILSCALE_AUTH_KEY" --hostname="gha-windows-rdp" --accept-dns=false

      - name: Configure Windows: enable Remote Desktop & disable NLA
        shell: powershell
        run: |
          Write-Host "Enabling Remote Desktop..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force

          Write-Host "Disabling Network Level Authentication (if required)..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force

          Write-Host "Enabling Remote Desktop firewall rules..."
          Get-NetFirewallRule -DisplayGroup "Remote Desktop" | ForEach-Object { Enable-NetFirewallRule -Name $_.Name }

          Restart-Service -Name TermService -Force -ErrorAction SilentlyContinue

      - name: Show Tailscale status (summary)
        shell: powershell
        run: |
          tailscale status

      - name: Done
        run: echo "RDP and Tailscale configured securely."
